#version: "2.1"
services:

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${appdata}/radarr/config:/config
      - ${movie_folder}:/movies
      - ${download_folder}:/downloads
    ports:
      - ${radarr_port}:7878
    restart: unless-stopped
    networks:
      - arr_stack

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${appdata}/sonarr/config:/config
      - ${show_folder}:/shows
      - ${download_folder}:/downloads
    ports:
      - ${sonarr_port}:8989
    restart: unless-stopped
    networks:
      - arr_stack

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${appdata}/bazarr/config:/config
      - ${movie_folder}:/movies
      - ${show_folder}:/shows
    ports:
      - ${bazarr_port}:6767
    restart: unless-stopped
    networks:
      - arr_stack

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /${appdata}/lidarr:/config
      - ${music_folder}:/music
      - ${download_folder}:/downloads
    ports:
      - ${lidarr_port}:8686
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - ${jellyseerr_port}:5055
    volumes:
      - ${appdata}/jellyseer:/app/config
    restart: unless-stopped
    networks:
      - arr_stack

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${appdata}/prowlarr:/config
    ports:
      - ${prowlarr_port}:9696
    restart: unless-stopped
    networks:
      - arr_stack

networks:
  arr_stack:
    external: true
