services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - ${metube_port}:8081
    volumes:
      - ${download_folder}:/downloads
    networks:
      - dockernet
networks:
  dockernet:
    external: true
