#version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${appdata}:/app/data
      - ${env_location}:/mnt/appdata/.env
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
    restart: unless-stopped
    networks:
      - dockernet
networks:
  dockernet:
    external: true
